name: Scrape EduRec Website Daily at 5 am

on:
  schedule:
    - cron: 0  21 * * *
  workflow_dispatch:

jobs: 
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --omit=optional
        working-directory: PlayWright
      - name: Run Scraper
        run: node PlayWright/scripts/edurecScraper.spec.mjs
        env:
          SUPABASE_PROJECT_KEY: ${{ secrets.SUPABASE_PROJECT_KEY }}
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
          SUPABASE_DATABASE_URL=: ${{ secrets.SUPABASE_PROJECT_URL }}

  upload:
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --omit=optional
        working-directory: PlayWright
      - name: Run Push Data to Database Script
        run: node PlayWright/scripts/bucketToDatabase.mjs
        env:
          SUPABASE_PROJECT_KEY: ${{ secrets.SUPABASE_PROJECT_KEY }}
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
          SUPABASE_DATABASE_URL=: ${{ secrets.SUPABASE_PROJECT_URL }}


